// Sample book data for Akabir Prokashoni islamic
export const sampleBooks = [
  {
    id: 'b1',
    slug: 'ghure-darao',
    title: 'ঘুরে দাঁড়াও',
    author: 'ওয়ায়েল ইব্রাহিম',
    authorSlug: 'wayel-ibrahim',
    publisher: 'আকাবির প্রকাশনী',
    category: 'আত্ম-উন্নয়ন',
    categorySlug: 'self-development',
    price: 257,
    originalPrice: 343,
    discount: 25,
    rating: 4.8,
    reviewCount: 234,
    stock: 45,
    isbn: '978-984-001-001-0',
    pages: 224,
    language: 'বাংলা',
    edition: '৩য় সংস্করণ',
    cover: '/images/books/ghure-darao.jpg',
    tags: ['আত্ম-উন্নয়ন', 'মোটিভেশন', 'ইসলামিক'],
    description: 'ঘুরে দাঁড়াও বইটি একজন পথভ্রষ্ট যুবককে কীভাবে সঠিক পথে ফিরে আসতে পারে তার অনুপ্রেরণামূলক গল্প। লেখক ওয়ায়েল ইব্রাহিম নিজের জীবনের অভিজ্ঞতা থেকে বলেছেন কীভাবে একজন মানুষ তার জীবনকে সম্পূর্ণ বদলে দিতে পারে।',
    authorBio: 'ওয়ায়েল ইব্রাহিম একজন আন্তর্জাতিক খ্যাতিসম্পন্ন ইসলামিক স্কলার ও মোটিভেশনাল স্পিকার। তিনি অস্ট্রেলিয়ায় বসবাস করেন।',
    isTrending: true,
    isNewRelease: false,
    isPreOrder: false,
  },
  {
    id: 'b2',
    slug: 'paradoxical-sajid',
    title: 'প্যারাডক্সিক্যাল সাজিদ',
    author: 'আরিফ আজাদ',
    authorSlug: 'arif-azad',
    publisher: 'গার্ডিয়ান পাবলিকেশনস',
    category: 'ইসলামিক',
    categorySlug: 'islamic',
    price: 250,
    originalPrice: 350,
    discount: 29,
    rating: 4.9,
    reviewCount: 1520,
    stock: 120,
    isbn: '978-984-001-002-0',
    pages: 160,
    language: 'বাংলা',
    edition: '১০ম সংস্করণ',
    cover: '/images/books/paradoxical-sajid.jpg',
    tags: ['ইসলামিক', 'দর্শন', 'বিজ্ঞান ও ধর্ম'],
    description: 'একটি ছোট্ট বই কিন্তু তার প্রভাব বিশাল। সাজিদ নামের একজন যুবক তার বন্ধুদের সাথে বিভিন্ন বিষয়ে আলোচনা করে। নাস্তিকতা, বিবর্তনবাদ, ইসলামের যুক্তিগ্রাহ্যতা — সব কিছু নিয়ে সাজিদের প্যারাডক্সিক্যাল চিন্তাভাবনা।',
    authorBio: 'আরিফ আজাদ বাংলাদেশের অন্যতম জনপ্রিয় তরুণ লেখক। তাঁর লেখা বইগুলো বাংলাদেশের বেস্টসেলার তালিকায় শীর্ষে থাকে।',
    isTrending: true,
    isNewRelease: false,
    isPreOrder: false,
  },
  {
    id: 'b3',
    slug: 'ek-nojore-quran',
    title: 'এক নজরে কুরআন',
    author: 'মিজানুর রহমান আজহারি',
    authorSlug: 'mizanur-rahman-azhari',
    publisher: 'আকাবির প্রকাশনী',
    category: 'কুরআন ও তাফসীর',
    categorySlug: 'quran-tafsir',
    price: 1590,
    originalPrice: 1870,
    discount: 15,
    rating: 4.7,
    reviewCount: 890,
    stock: 30,
    isbn: '978-984-001-003-0',
    pages: 640,
    language: 'বাংলা',
    edition: '১ম সংস্করণ',
    cover: '/images/books/ek-nojore-quran.jpg',
    tags: ['কুরআন', 'তাফসীর', 'ইসলামিক'],
    description: 'কুরআনের সম্পূর্ণ পরিচয় একটি মাত্র বইয়ে। প্রতিটি সূরার মূল বার্তা, প্রেক্ষাপট এবং শিক্ষা সংক্ষিপ্তভাবে উপস্থাপিত হয়েছে এই অনন্য গ্রন্থে।',
    authorBio: 'মিজানুর রহমান আজহারি একজন বাংলাদেশি ইসলামিক স্কলার ও বক্তা। তিনি আল-আজহার বিশ্ববিদ্যালয়ের স্নাতক।',
    isTrending: true,
    isNewRelease: true,
    isPreOrder: false,
  },
  {
    id: 'b4',
    slug: 'human-being',
    title: 'হিউম্যান বিয়িং',
    author: 'ইফতেখার সিফাত',
    authorSlug: 'iftekhar-sifat',
    publisher: 'সমকালীন প্রকাশনী',
    category: 'চিন্তা ও দর্শন',
    categorySlug: 'philosophy',
    price: 217,
    originalPrice: 290,
    discount: 25,
    rating: 4.6,
    reviewCount: 456,
    stock: 67,
    isbn: '978-984-001-004-0',
    pages: 280,
    language: 'বাংলা',
    edition: '২য় সংস্করণ',
    cover: '/images/books/human-being.jpg',
    tags: ['চিন্তা', 'দর্শন', 'সমাজ'],
    description: 'শতাব্দীর বুদ্ধিবৃত্তিক দাসত্ব নিয়ে লেখা এক অসাধারণ বই। আধুনিক বিশ্বে মানুষ কীভাবে চিন্তার স্বাধীনতা হারাচ্ছে তার বিশ্লেষণ।',
    authorBio: 'ইফতেখার সিফাত একজন চিন্তাশীল লেখক যিনি সমাজ, রাজনীতি ও দর্শন নিয়ে লেখালেখি করেন।',
    isTrending: false,
    isNewRelease: false,
    isPreOrder: false,
  },
  {
    id: 'b5',
    slug: 'double-standard',
    title: 'ডাবল স্ট্যান্ডার্ড ২.০',
    author: 'ডা. শামসুল আরেফীন',
    authorSlug: 'dr-shamsul-arefin',
    publisher: 'সমকালীন প্রকাশনী',
    category: 'চিন্তা ও দর্শন',
    categorySlug: 'philosophy',
    price: 290,
    originalPrice: 392,
    discount: 26,
    rating: 4.5,
    reviewCount: 890,
    stock: 34,
    isbn: '978-984-001-005-0',
    pages: 320,
    language: 'বাংলা',
    edition: '৫ম সংস্করণ',
    cover: '/images/books/double-standard.jpg',
    tags: ['সমাজ', 'চিন্তা', 'পাশ্চাত্য সভ্যতা'],
    description: 'পশ্চিমা সভ্যতার দ্বিমুখী নীতি ও তার প্রভাব নিয়ে লেখা একটি তথ্যবহুল বই। মুক্তচিন্তার নামে কীভাবে একপেশে দৃষ্টিভঙ্গি চাপিয়ে দেওয়া হচ্ছে।',
    authorBio: 'ডা. শামসুল আরেফীন একজন চিকিৎসক ও লেখক। সমাজবিশ্লেষণমূলক লেখালেখিতে তিনি বিশেষভাবে পরিচিত।',
    isTrending: true,
    isNewRelease: false,
    isPreOrder: false,
  },
  {
    id: 'b6',
    slug: 'adorsho-muslim',
    title: 'আদর্শ মুসলিম',
    author: 'ড. মুহাম্মদ আলী আল হাশেমী',
    authorSlug: 'dr-ali-hashemi',
    publisher: 'আকাবির প্রকাশনী',
    category: 'ইসলামিক',
    categorySlug: 'islamic',
    price: 450,
    originalPrice: 900,
    discount: 50,
    rating: 4.9,
    reviewCount: 2100,
    stock: 88,
    isbn: '978-984-001-006-0',
    pages: 480,
    language: 'বাংলা',
    edition: '৭ম সংস্করণ',
    cover: '/images/books/adorsho-muslim.jpg',
    tags: ['ইসলামিক', 'আদর্শ', 'জীবনযাপন'],
    description: 'একজন আদর্শ মুসলিমের জীবনযাপনের পূর্ণাঙ্গ গাইডলাইন। ব্যক্তিগত, পারিবারিক ও সামাজিক জীবনে ইসলামী আদর্শের প্রতিফলন।',
    authorBio: 'ড. মুহাম্মদ আলী আল হাশেমী একজন প্রখ্যাত আরব লেখক ও ইসলামিক চিন্তাবিদ।',
    isTrending: true,
    isNewRelease: false,
    isPreOrder: false,
  },
  {
    id: 'b7',
    slug: 'spy-stories-2',
    title: 'স্পাই স্টোরিজ ২',
    author: 'মোজাম্মেল হোসেন ত্বোহা',
    authorSlug: 'mozammel-toha',
    publisher: 'ভাষান্তর প্রকাশনী',
    category: 'থ্রিলার',
    categorySlug: 'thriller',
    price: 350,
    originalPrice: 500,
    discount: 30,
    rating: 4.7,
    reviewCount: 670,
    stock: 55,
    isbn: '978-984-001-007-0',
    pages: 384,
    language: 'বাংলা',
    edition: '১ম সংস্করণ',
    cover: '/images/books/spy-stories.jpg',
    tags: ['থ্রিলার', 'গুপ্তচর', 'অ্যাডভেঞ্চার'],
    description: 'বিশ্বের সবচেয়ে রোমাঞ্চকর গুপ্তচরবৃত্তির সত্য ঘটনা অবলম্বনে রচিত। গোপন মিশন, ডাবল এজেন্ট, কোল্ড ওয়ারের অজানা অধ্যায়।',
    authorBio: 'মোজাম্মেল হোসেন ত্বোহা একজন জনপ্রিয় অনুবাদক ও থ্রিলার লেখক।',
    isTrending: false,
    isNewRelease: true,
    isPreOrder: false,
  },
  {
    id: 'b8',
    slug: 'nostalgia-nineties',
    title: 'নস্টালজিয়ায় নব্বই ২.০',
    author: 'মোঃ মনোয়ার হোসেন বুলবুল',
    authorSlug: 'monowar-hossain',
    publisher: 'আকাবির প্রকাশনী',
    category: 'উপন্যাস',
    categorySlug: 'novel',
    price: 520,
    originalPrice: 800,
    discount: 35,
    rating: 4.4,
    reviewCount: 189,
    stock: 40,
    isbn: '978-984-001-008-0',
    pages: 350,
    language: 'বাংলা',
    edition: '১ম সংস্করণ',
    cover: '/images/books/nostalgia.jpg',
    tags: ['উপন্যাস', 'নস্টালজিয়া', 'নব্বই দশক'],
    description: 'নব্বই দশকের বাংলাদেশের স্মৃতিচারণ। সেই সময়ের খেলাধুলা, সংস্কৃতি, রাজনীতি ও জীবনযাপনের এক অনন্য চিত্র।',
    authorBio: 'মোঃ মনোয়ার হোসেন বুলবুল একজন সাহিত্যিক ও স্মৃতিচারণমূলক লেখক।',
    isTrending: false,
    isNewRelease: false,
    isPreOrder: true,
  },
];

export const categories = [
  { name: 'ইসলামিক', slug: 'islamic', icon: '🕌', count: 2450, color: '#0D6B3F' },
  { name: 'আত্ম-উন্নয়ন', slug: 'self-development', icon: '🚀', count: 560, color: '#D4A843' },
  { name: 'উপন্যাস', slug: 'novel', icon: '📖', count: 890, color: '#6366F1' },
  { name: 'থ্রিলার', slug: 'thriller', icon: '🔍', count: 340, color: '#EF4444' },
  { name: 'শিশু-কিশোর', slug: 'children', icon: '🧒', count: 670, color: '#F59E0B' },
  { name: 'চিন্তা ও দর্শন', slug: 'philosophy', icon: '💭', count: 220, color: '#8B5CF6' },
  { name: 'ইতিহাস', slug: 'history', icon: '🏛️', count: 430, color: '#059669' },
  { name: 'কুরআন ও তাফসীর', slug: 'quran-tafsir', icon: '📗', count: 310, color: '#0D6B3F' },
  { name: 'হাদিস', slug: 'hadith', icon: '📚', count: 180, color: '#B45309' },
  { name: 'প্রোগ্রামিং', slug: 'programming', icon: '💻', count: 150, color: '#2563EB' },
];

export const popularAuthors = [
  { name: 'আরিফ আজাদ', slug: 'arif-azad', image: '/images/authors/arif-azad.jpg', bookCount: 12 },
  { name: 'মিজানুর রহমান আজহারি', slug: 'mizanur-rahman-azhari', image: '/images/authors/azhari.jpg', bookCount: 8 },
  { name: 'ড. খোন্দকার আব্দুল্লাহ জাহাঙ্গীর', slug: 'dr-jahangir', image: '/images/authors/jahangir.jpg', bookCount: 45 },
  { name: 'ডা. শামসুল আরেফীন', slug: 'dr-shamsul-arefin', image: '/images/authors/arefin.jpg', bookCount: 6 },
  { name: 'ওয়ায়েল ইব্রাহিম', slug: 'wayel-ibrahim', image: '/images/authors/wayel.jpg', bookCount: 4 },
  { name: 'ইফতেখার সিফাত', slug: 'iftekhar-sifat', image: '/images/authors/sifat.jpg', bookCount: 3 },
];

export const orderStatuses = [
  { key: 'placed', label: 'অর্ডার গৃহীত', icon: '📋' },
  { key: 'confirmed', label: 'নিশ্চিত করা হয়েছে', icon: '✅' },
  { key: 'packaging', label: 'প্যাকেজিং হচ্ছে', icon: '📦' },
  { key: 'shipped', label: 'শিপড হয়েছে', icon: '🚚' },
  { key: 'delivered', label: 'ডেলিভারড', icon: '🎉' },
];

export const districts = [
  'ঢাকা', 'চট্টগ্রাম', 'রাজশাহী', 'সিলেট', 'খুলনা',
  'বরিশাল', 'রংপুর', 'ময়মনসিংহ', 'কুমিল্লা', 'গাজীপুর',
  'নারায়ণগঞ্জ', 'যশোর', 'দিনাজপুর', 'বগুড়া', 'পাবনা',
];
